const helpText = {
    "age1": "Enter your current age in years. This sets the starting point for your timeline.",
    "ret1": "Enter the age you expect to stop working. Your living expenses and income will adjust at this point.",
    "sal1": "Your current annual gross salary, before tax and deductions. This determines your mortgage affordability and net income.",
    "age2": "Enter your partner's current age in years.",
    "sal2": "Your partner's current annual gross salary, before tax and deductions.",
    "has_sl1": "Select 'Yes' if you are currently making repayments on a student loan.",
    "sl1": "The total remaining balance of your student loan debt.",
    "slp1": "The specific student loan plan you are on. This determines your repayment threshold and interest rate.",
    "has_sl2": "Select 'Yes' if your partner is currently making repayments on a student loan.",
    "sl2": "The total remaining balance of your partner's student loan debt.",
    "slp2": "The specific student loan plan your partner is on.",
    "has_pen1": "Select 'Yes' if you have an active workplace or personal pension.",
    "pval1": "The current total value of your pension pot(s).",
    "pee1": "The percentage of your salary that you contribute to your pension.",
    "per1": "The percentage of your salary that your employer contributes to your pension.",
    "has_pen2": "Select 'Yes' if your partner has an active workplace or personal pension.",
    "pval2": "The current total value of your partner's pension pot(s).",
    "pee2": "The percentage of your partner's salary that they contribute.",
    "per2": "The percentage of your partner's salary that their employer contributes.",
    "cash": "The total amount of cash savings and liquid investments you hold.",
    "rent": "The monthly rent you currently pay.",
    "ex_pre": "Your estimated monthly living expenses (excluding rent/mortgage) while you are working.",
    "ex_post": "Your estimated monthly living expenses (excluding rent/mortgage) after you retire.",
    "hp": "The target purchase price of the property you'd like to buy.",
    "ftb": "Select 'Yes' if you are a first-time buyer. This affects the Stamp Duty you will pay.",
    "fees": "Expected legal, moving, and survey fees associated with buying the home.",
    "maint": "Expected annual maintenance and upkeep costs for the home.",
    "sp1": "The expected annual State Pension amount you will receive from the government.",
    "tfc1": "Whether you plan to take tax-free cash from your pension upon retirement.",
    "sp2": "The expected annual State Pension amount your partner will receive.",
    "tfc2": "Whether your partner plans to take tax-free cash from their pension.",
    "save_pen": "The percentage of your monthly disposable income you choose to invest into your pension."
};
